#!/usr/bin/env bash

verde="\e[0;32m\033[1m"
finColor="\033[0m\e[0m"
rojo="\e[0;31m\033[1m"
azul="\e[0;34m\033[1m"
amarillo="\e[0;33m\033[1m"
violeta="\e[0;35m\033[1m" 
turquesa="\e[0;36m\033[1m"
gris="\e[0;37m\033[1m"


function banner(){
	    echo -e "\n${azul}#########${finColor}\t ${gris}$@${finColor}\t${azul}#########${finColor}\n"

}
function resultado(){
	    echo -e "\n${azul}-----------------${finColor}\n ${gris}$@${finColor}\n${azul}-----------------${finColor}\n"

}

function informacion(){
	    echo -e "${amarillo}[i]${finColor}\t ${gris}$@${finColor} "

}

function error(){
	    echo -e "\n${rojo}[!]${finColor}\t ${rojo}$@${finColor}\n"

}

function consulta(){
	    echo -e "\n${amarillo}[?]\t $@${finColor}\n"

}
